version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - '10.22'
                - '12.18'
                - '14.10'
                - '15.0'
