version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
workflows:
  node-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - 10
                - 11
                - 12
                - 14
